name: Create Release & Tag
on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set current date as env variable
      id: date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Create Release & Tag 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.BOT_GITACTION }}
      with: 
        tag_name: "v.${{ steps.date.outputs.NOW }}"
        release_name: "v.${{ steps.date.outputs.NOW }}"
